#!/usr/bin/env python3
"""Aggregate daily memories of a given month into a monthly draft.

Read-only: prints the draft to stdout. The agent reviews, decides what
gets promoted into palace/learned_patterns, fills `promoted_to:` on each
daily, then writes the actual monthly/YYYY/MM.md file.

Why read-only: monthly aggregation is a real judgment exercise — it's
where tentative observations from multiple days get evaluated for promotion
to long-term reflections. Automating this without human review produces
shallow summaries that drift.

Usage:
  python3 tools/aggregate-monthly.py             # this month
  python3 tools/aggregate-monthly.py 2026-05     # specific month
"""

from __future__ import annotations

import argparse
import calendar
import pathlib
import sys
from datetime import datetime

import _lib as lib

# Reuse section extractor
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from importlib import import_module  # noqa: E402

_agg_daily = import_module("aggregate-daily")
extract_sections = _agg_daily.extract_sections


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("month", nargs="?", default=None, help="YYYY-MM (default: this month)")
    ap.add_argument("--root", type=pathlib.Path, default=lib.DEFAULT_ROOT)
    args = ap.parse_args()

    if args.month:
        try:
            year, mo = (int(x) for x in args.month.split("-"))
        except ValueError:
            print(f"error: bad month {args.month!r}, expected YYYY-MM", file=sys.stderr)
            return 2
    else:
        t = lib.today()
        year, mo = t.year, t.month

    daily_dir = args.root / "daily" / f"{year:04d}" / f"{mo:02d}"
    if not daily_dir.exists():
        print(f"# No daily entries for {year}-{mo:02d}\n(directory not found: {daily_dir})")
        return 0

    dailies = [lib.load(p) for p in sorted(daily_dir.glob("*.md"))]
    if not dailies:
        print(f"# No daily entries for {year}-{mo:02d}\n")
        return 0

    last_day = calendar.monthrange(year, mo)[1]
    print(f"# Monthly Draft — {year}-{mo:02d}\n")
    print("> Generated by aggregate-monthly.py. **Review before saving** to "
          f"`monthly/{year:04d}/{mo:02d}.md`.\n")
    print(f"## Sources ({len(dailies)} daily entries)")
    for d in dailies:
        print(f"- {d.rel_path}")
    print()

    print("## Suggested frontmatter")
    print("```yaml")
    print(f"name: monthly-{year}-{mo:02d}")
    print(f"description: <{year}-{mo:02d} 月度认知状态总结>")
    print("type: monthly")
    print(f"created_at: {year}-{mo:02d}-{last_day:02d}")
    print(f"updated_at: {year}-{mo:02d}-{last_day:02d}")
    print("confidence: 0.85")
    print("importance: <0..1>")
    print("status: active")
    print("evidence:")
    for d in dailies:
        print(f"  - {d.rel_path}")
    print("promoted_to: []  # fill with palace/* targets after reflection review")
    print("```\n")

    aggregated: dict[str, list[tuple[str, str]]] = {}
    for d in dailies:
        sections = extract_sections(d.body)
        for hdr, content in sections.items():
            if not content.strip():
                continue
            aggregated.setdefault(hdr, []).append((d.rel_path, content))

    # Order by likely importance for monthly review
    priority = [
        "Summary", "Important Events", "Promoted Memories", "Decisions Confirmed",
        "Decisions Reversed / Superseded", "New Preferences / Patterns",
        "Open Questions", "Conflicts Pending",
    ]
    ordered = [h for h in priority if h in aggregated] + [
        h for h in aggregated if h not in priority
    ]

    for hdr in ordered:
        print(f"## {hdr}")
        for src, content in aggregated[hdr]:
            print(f"\n_from `{src}`:_")
            print(content)
        print()

    print("\n## Reviewer checklist (monthly-specific)")
    print("- [ ] Patterns appearing ≥3 distinct days → candidate for `palace/learned_patterns.md`")
    print("- [ ] Tentative preferences seen across multiple days → upgrade in `palace/preferences.md`")
    print("- [ ] Decisions reversed within month: keep both with proper supersede chain")
    print("- [ ] Identify which daily entries can now be considered for compression")
    print("- [ ] Fill `promoted_to:` on this monthly draft with palace/entity targets")
    print("- [ ] Update each source daily's `promoted_to:` if its content promoted further")
    print("- [ ] Update MEMORY.md index with link to the new monthly entry")
    return 0


if __name__ == "__main__":
    sys.exit(main())
