#!/usr/bin/env python3
"""Aggregate session memories of a given date into a draft daily memory.

This tool PRINTS a draft to stdout. It does NOT write the daily file — the
agent should review the draft, then write it explicitly with proper
frontmatter (including `evidence:` linking back to the sessions, and updating
`promoted_to:` on each session).

Why this is read-only by default: aggregation involves judgment calls
(deduping, classifying patterns as tentative vs. confirmed, detecting
conflicts). Automating that without a human-in-the-loop produces sloppy
daily memories.

Usage:
  python3 tools/aggregate-daily.py             # today
  python3 tools/aggregate-daily.py 2026-05-13  # specific date
"""

from __future__ import annotations

import argparse
import pathlib
import re
import sys
from datetime import date, datetime

import _lib as lib


SECTION_RE = re.compile(r"^##\s+(.+?)\s*$", re.MULTILINE)


def extract_sections(body: str) -> dict[str, str]:
    """Split a markdown body into {header: content} keyed by H2."""
    out: dict[str, str] = {}
    matches = list(SECTION_RE.finditer(body))
    for i, m in enumerate(matches):
        header = m.group(1).strip()
        start = m.end()
        end = matches[i + 1].start() if i + 1 < len(matches) else len(body)
        out[header] = body[start:end].strip()
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("date", nargs="?", default=None, help="YYYY-MM-DD (default: today)")
    ap.add_argument("--root", type=pathlib.Path, default=lib.DEFAULT_ROOT)
    args = ap.parse_args()

    if args.date:
        try:
            target = datetime.strptime(args.date, "%Y-%m-%d").date()
        except ValueError:
            print(f"error: bad date {args.date!r}, expected YYYY-MM-DD", file=sys.stderr)
            return 2
    else:
        target = lib.today()

    sessions_dir = (
        args.root / "sessions" / f"{target.year:04d}" / f"{target.month:02d}" / f"{target.day:02d}"
    )
    if not sessions_dir.exists():
        print(f"# No sessions for {target}\n(directory not found: {sessions_dir})")
        return 0

    sessions = [lib.load(p) for p in sorted(sessions_dir.glob("session_*.md"))]
    if not sessions:
        print(f"# No sessions for {target}\n")
        return 0

    print(f"# Daily Draft — {target}\n")
    print("> Generated by aggregate-daily.py. **Review before saving** to "
          f"`daily/{target.year:04d}/{target.month:02d}/{target.day:02d}.md`.\n")
    print(f"## Sources ({len(sessions)} session(s))")
    for s in sessions:
        print(f"- {s.rel_path}")
    print()

    print("## Suggested frontmatter")
    print("```yaml")
    print(f"name: daily-{target}")
    print("description: <一句话总结当日认知状态>")
    print("type: daily")
    print(f"created_at: {target}")
    print(f"updated_at: {target}")
    print("confidence: 0.85")
    print("importance: <0..1>")
    print("status: active")
    print("evidence:")
    for s in sessions:
        print(f"  - {s.rel_path}")
    print("promoted_to: []  # fill in after promoting facts to palace/entity")
    print("```\n")

    aggregated: dict[str, list[tuple[str, str]]] = {}
    for s in sessions:
        sections = extract_sections(s.body)
        for hdr, content in sections.items():
            if not content.strip():
                continue
            aggregated.setdefault(hdr, []).append((s.rel_path, content))

    for hdr, chunks in aggregated.items():
        print(f"## {hdr}")
        for src, content in chunks:
            print(f"\n_from `{src}`:_")
            print(content)
        print()

    print("\n## Reviewer checklist")
    print("- [ ] Dedupe overlapping facts across sessions")
    print("- [ ] Classify new observations: tentative (1 occurrence) vs. candidate (≥2) vs. confirmed (≥3)")
    print("- [ ] Detect conflicts with existing palace/entity memories — run `find-conflicts.py`")
    print("- [ ] Decide which facts get promoted to palace/entity (fill `promoted_to:`)")
    print("- [ ] Update each source session's `promoted_to:` field to point at this daily")
    print("- [ ] Update MEMORY.md index with link to this daily")

    return 0


if __name__ == "__main__":
    sys.exit(main())
