#!/usr/bin/env python3
"""Aggregate monthly memories of a given year into a yearly draft.

Read-only: prints the draft to stdout. The agent reviews and writes
the actual yearly/YYYY.md file.

Yearly aggregation has the lowest bar for automation — most of the
useful information has already been promoted to palace by this point.
The yearly is more of a high-level trajectory than a content store:
"what projects were active", "what stable preferences solidified",
"what got abandoned".

Usage:
  python3 tools/aggregate-yearly.py             # this year
  python3 tools/aggregate-yearly.py 2026        # specific year
"""

from __future__ import annotations

import argparse
import pathlib
import sys
from datetime import datetime

import _lib as lib

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from importlib import import_module  # noqa: E402

_agg_daily = import_module("aggregate-daily")
extract_sections = _agg_daily.extract_sections


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("year", nargs="?", type=int, default=None,
                    help="YYYY (default: this year)")
    ap.add_argument("--root", type=pathlib.Path, default=lib.DEFAULT_ROOT)
    args = ap.parse_args()

    year = args.year if args.year else lib.today().year

    monthly_dir = args.root / "monthly" / f"{year:04d}"
    if not monthly_dir.exists():
        print(f"# No monthly entries for {year}\n(directory not found: {monthly_dir})")
        return 0

    monthlies = [lib.load(p) for p in sorted(monthly_dir.glob("*.md"))]
    if not monthlies:
        print(f"# No monthly entries for {year}\n")
        return 0

    print(f"# Yearly Draft — {year}\n")
    print("> Generated by aggregate-yearly.py. **Review before saving** to "
          f"`yearly/{year:04d}.md`.\n")
    print(f"## Sources ({len(monthlies)} monthly entries)")
    for m in monthlies:
        print(f"- {m.rel_path}")
    print()

    print("## Suggested frontmatter")
    print("```yaml")
    print(f"name: yearly-{year}")
    print(f"description: <{year} 年度高层轨迹>")
    print("type: yearly")
    print(f"created_at: {year}-12-31")
    print(f"updated_at: {year}-12-31")
    print("confidence: 0.85")
    print("importance: 1.0")
    print("status: active")
    print("evidence:")
    for m in monthlies:
        print(f"  - {m.rel_path}")
    print("promoted_to: []")
    print("```\n")

    # Pull a few high-signal section types only — yearly should be concise.
    high_signal = {
        "Summary",
        "Decisions Confirmed",
        "Promoted Memories",
        "New Preferences / Patterns",
        "Decisions Reversed / Superseded",
    }
    aggregated: dict[str, list[tuple[str, str]]] = {}
    for m in monthlies:
        sections = extract_sections(m.body)
        for hdr, content in sections.items():
            if hdr not in high_signal or not content.strip():
                continue
            aggregated.setdefault(hdr, []).append((m.rel_path, content))

    for hdr in [h for h in high_signal if h in aggregated]:
        print(f"## {hdr}")
        for src, content in aggregated[hdr]:
            print(f"\n_from `{src}`:_")
            print(content)
        print()

    print("\n## Reviewer checklist (yearly-specific)")
    print("- [ ] Highlight project trajectories: started / completed / abandoned")
    print("- [ ] Note stable preferences vs. preferences that drifted")
    print("- [ ] List 3–5 most consequential decisions of the year")
    print("- [ ] After saving, consider archiving very old daily entries (keep monthly + yearly)")
    print("- [ ] Update MEMORY.md with the yearly link")
    return 0


if __name__ == "__main__":
    sys.exit(main())
